# 使用官方Go镜像作为运行环境
FROM golang:1.25-alpine

# 安装git
RUN apk add --no-cache git

# 设置工作目录
WORKDIR /app

# 复制源代码
COPY . .

# 构建应用
RUN CGO_ENABLED=0 GOOS=linux go build -o binance-proxy .

# 暴露端口
EXPOSE 8082

# 运行应用
CMD ["./binance-proxy"]